### PR TITLE
Decapitalization

### PR DESCRIPTION
**Pull request by DarioEMeloD**
That's everything I could find, plus some changes to match newer games. Also changed Togetic's pallete to Togekiss'.

### CODE REVIEW

**Comment by TheFakeMateo** [comment]
Sounds good. Out of curiosity, what were the "changes to match the newer games" you added?

**Comment by DarioEMeloD** [comment]
Minor stuff, like Evade>Evasion, Contents>Pokédex, Data>Info, removed the "/" in some status screens; and mostly menu options, like Cancel>Back.

**Comment by TheFakeMateo** [comment]
Gotcha. When changing the length of stuff did you make sure it won't cause text to overflow the textboxes? Not sure if that will be an issue with any of them or not, my phone isn't wanting to render the whole diff for me to really look, stops loading while we're in the Pokedex data.

**Comment by DarioEMeloD** [comment]
I haven't tested all of it but I made sure to keep everything inside the textbox. What I checked seemed to be fine.

**Comment by TheFakeMateo** [comment]
I appreciate the help btw, modernized menu options are definitely part of the plan. And eventually I'm going to need to redo the stats screens anyway, to make room for displaying both Special stats after I split them, showing held item, etc

**Comment by DarioEMeloD** [comment]
No problem, I was messing around with the font and some graphics, and decided to do this so it looks better, it wasn't much. Btw, the graphics I changed are FRLG-styled, in case you want to use them (HP bar, font, badges, map...)

**Comment by TheFakeMateo** [comment]
Sure, I'll take a look. I'm eventually going to be redoing the trainer card to look more like FrLg anyway, and have a second page for the Johto badges. And I was thinking that once I add color, I'd go for the HGSS style town map. Also, once it's gbc, I'm planning to switch to using more of the tilesets I made for Pokémon Christmas  (just not snowy) which are all based on FrLg. So these changes you mentioned sound good in theory.

**Comment by TheFakeMateo** [comment]
Never got a chance to really review this yesterday after work, wasn't home much. Assuming nothing weird comes up today I should get to it tonight.

**Comment by TheFakeMateo** [comment]
Tried to look through this. Looking good, but I'll leave it open in case you have any more commits to push like you did the other day.

**Comment by DarioEMeloD** [comment]
Don't worry, I keep finding more stuff, I'll let you know.

**Comment by TheFakeMateo** [comment]
Been a while since I saw you adding to this. Ready for it to be merged, or are you still needing to add to this request?

**Comment by DarioEMeloD** [comment]
Yeah it's ready, I haven't played in a while, tho I tested almost everything except the Hall of Fame, but I guess it should be ok.

**Comment by TheFakeMateo** [comment]
Sounds good then. I just wanted to wait until you were done adding commits for the sake of convenience for both of us.

**Pull request merged**
